project:
  type: website
  render:
  - '*.qmd'
  - '*.ipynb'
  - 'examples/*.ipynb'
  - 'pages/*.qmd'
  resources:
  - authors.yml
  - CITATION.cff
profile:
  default: warm-journal
  group:
    - [warm-journal, technical-notebook]
execute:
  freeze: auto
website:
  favicon: "_extensions/surrogate-sci/ss-pub-theme/assets/logo_surrogate_mark.svg"
  twitter-card: true
  open-graph: true
  navbar:
    collapse-below: xl
    pinned: false
    title: false
    left:
    - text: '{{< iconify qlementine-icons:version-control-16 >}}'
      menu:
      - text: v01 (latest)
        href: index.ipynb
    - text: '{{< iconify nrk:back >}} Back to Pub'
      href: index.ipynb
    - text: Demo
      href: /examples/demo.html
    right:
    - text: FAQ
      href: pages/FAQ.qmd
    - text: Reproduce this pub
      href: pages/SETUP.qmd
    - text: Cite this pub
      href: "#"
    - text: Contribute
      href: pages/CONTRIBUTING.qmd
    tools:
    - icon: github
      href: https://github.com/{{< var pub.org >}}/{{< var pub.repo >}}
    logo: "_extensions/surrogate-sci/ss-pub-theme/assets/logo_surrogate_mark.svg"
    logo-href: https://github.com/surrogate-sci
    background: '#F5F0E2'
    search: true
  page-footer:
    background: '#30332F'
    border: false
    left: '[![](/_extensions/surrogate-sci/ss-pub-theme/assets/logo_surrogate_mark.svg){fig-alt="Surrogate Science" width=65px}](https://github.com/surrogate-sci)

      Copyright 2026, Surrogate Science

      '
    right:
    - icon: github
      href: https://github.com/surrogate-sci
  google-analytics: '{{< var pub.google_analytics_id >}}'
  cookie-consent:
    type: implied
    style: simple
format:
  surrogate-sci/ss-pub-theme-html:
    html-math-method: katex
shortcodes:
- _extensions/mcanouil/iconify/iconify.lua
filters:
- _extensions/pandoc-ext/abstract-section/abstract-section.lua
- _extensions/mcanouil/collapse-output/collapse-output.lua
- _extensions/filter-warnings/filter-warnings.lua
comments:
  giscus:
    repo: surrogate-sci/science-pub-template
    input-position: top
reference-location: margin
bibliography: ref.bib
csl: "_extensions/surrogate-sci/ss-pub-theme/assets/surrogate-science.csl"
code-annotations: hover
html-table-processing: none
demo-title: A brief syntax demo
